server:
  port: 7601

eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.3:7001/eureka
  instance:
    ip-address: 192.168.172.130
    instance-id: config-center-7601
    prefer-ip-address: true

spring:
  application:
    name: config-center-7601
  cloud:
    config:
      server:
        git:
          # uri: https://github.com/MagiDrag0n/microservice-final-config-center.git
          uri: https://gitee.com/magidrag0n/microservice-final-config-center.git
          username: magidragon@foxmail.com
          # password: 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
          password: Gitee0520
          default-label: master
